require("UI.UIBaseView")
UIUAVPartsSkillUpDialogPanelView = class("UIUAVPartsSkillUpDialogPanelView", UIBaseView)
UIUAVPartsSkillUpDialogPanelView.__index = UIUAVPartsSkillUpDialogPanelView
function UIUAVPartsSkillUpDialogPanelView:__InitCtrl()
  self.mText_Title = self:GetText("Root/GrpDialog/GrpTop/GrpText/TitleText")
  self.mBtn_BgClose = self:GetButton("Root/GrpBg/Btn_Close")
  self.mBtn_Close = UIUtils.GetTempBtn(self:GetRectTransform("Root/GrpDialog/GrpTop/GrpClose"))
  self.mImage_LeftUpIcon = self:GetImage("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpUAVIcon/GrpTacticSkill2DIcon/Img_Icon")
  self.mImage_ArmIcon = self:GetImage("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpUAVIcon/Grp3DModel/Img_3DModelIcon")
  self.mText_CostNum = self:GetText("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpUAVIcon/GrpCost/Text_Num")
  self.mText_ArmName = self:GetText("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpText/Text_Name")
  self.mText_NowLevel = self:GetText("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpLevelUp/GrpTextNow/Text_Level")
  self.mText_NextLevel = self:GetText("Root/GrpDialog/GrpCenter/GrpSkillInfo/GrpLevelUp/GrpTextSoon/Text_Level")
  self.mText_SkillDes = self:GetText("Root/GrpDialog/GrpCenter/GrpSkillUp/GrpAllSkillDescription/GrpDescription/Viewport/Content/Text_SkillUp")
  self.mTrans_ItemScript = self:GetRectTransform("Root/GrpDialog/GrpCenter/GrpConsume/GrpItem")
  self.mBtn_info = UIUtils.GetTempBtn(self:GetRectTransform("Root/GrpDialog/GrpCenter/GrpSkillInfo/BtnInfo"))
  self.mBtn_Confirm = UIUtils.GetTempBtn(self:GetRectTransform("Root/GrpDialog/GrpAction/BtnConfirm"))
  self.mBtn_Cancle = UIUtils.GetTempBtn(self:GetRectTransform("Root/GrpDialog/GrpAction/BtnCancel"))
  self.mTrans_SkillDetail = self:GetRectTransform("Root/GrpDialog/Trans_GrpSkillDetails")
  self.mBtn_DetailBgClose = self:GetButton("Root/GrpDialog/Trans_GrpSkillDetails/Btn_Close")
  self.mBtn_DetailClose = UIUtils.GetTempBtn(self:GetRectTransform("Root/GrpDialog/Trans_GrpSkillDetails/BtnInfo"))
  self.mText_DetailSkillDes = self:GetText("Root/GrpDialog/Trans_GrpSkillDetails/GrpAllSkillDescription/GrpDescribe/Viewport/Content/Text_Level1")
  self.mTrans_DetailLevelUpDes = self:GetRectTransform("Root/GrpDialog/Trans_GrpSkillDetails/GrpAllSkillDescription/GrpDescribe/Viewport/Content/GrpLevelDescription")
end
function UIUAVPartsSkillUpDialogPanelView:InitCtrl(root)
  self:SetRoot(root)
  self:__InitCtrl()
end
